// Generated by https://quicktype.io

import { typeProjectCategory } from ".";

export interface IGetProyect {
  data: Datum[];
  meta: Meta;
}

export interface Datum {
  id: number;
  attributes: DatumAttributes;
}

export interface DatumAttributes {
  Title: string;
  description: string;
  slug: string;
  urlDemo: string;
  urlGithub: string;
  category: typeProjectCategory;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  locale: string;
  ImageProyect: ImageProyect;
}

export interface ImageProyect {
  data: Data;
}

export interface Data {
  id: number;
  attributes: DataAttributes;
}

export interface DataAttributes {
  name: string;
  alternativeText: null | string;
  caption: null;
  width: number;
  height: number;
  formats: Formats;
  hash: string;
  ext: EXT;
  mime: MIME;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: ProviderMetadata;
  createdAt: string;
  updatedAt: string;
}

export enum EXT {
  // eslint-disable-next-line no-unused-vars
  PNG = ".png",
}

export interface Formats {
  large: Large;
  small: Large;
  medium: Large;
  thumbnail: Large;
}

export interface Large {
  ext: EXT;
  url: string;
  hash: string;
  mime: MIME;
  name: string;
  path: null;
  size: number;
  width: number;
  height: number;
  provider_metadata: ProviderMetadata;
}

export enum MIME {
  // eslint-disable-next-line no-unused-vars
  ImagePNG = "image/png",
}

export interface ProviderMetadata {
  public_id: string;
  resource_type: ResourceType;
}

export enum ResourceType {
  // eslint-disable-next-line no-unused-vars
  Image = "image",
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  start: number;
  limit: number;
  total: number;
}
